import {
  boolean,
  date,
  integer,
  jsonb,
  pgTable,
  serial,
  text,
  timestamp,
} from "drizzle-orm/pg-core";

/** The AI fit-analysis pass's verdict on how well a job matches the candidate. */
export type FitVerdict = "strong" | "good" | "stretch" | "poor";

/**
 * Shape stored in `job_listings.fit_analysis` (lib/ai/fit-analysis.ts).
 * Mirrors the `fitAnalysis` object in lib/api-spec/openapi.yaml.
 */
export type FitAnalysis = {
  verdict: FitVerdict;
  /** 3-5 concrete strengths matching this specific posting. */
  greenFlags: string[];
  /** 0-4 real concerns (seniority mismatch, visa/location, missing must-haves). */
  redFlags: string[];
  /** 0-4 skills the posting asks for that are absent from the resume. */
  gaps: string[];
};

export const jobListingsTable = pgTable("job_listings", {
  id: serial("id").primaryKey(),
  source: text("source").notNull(),
  title: text("title").notNull(),
  company: text("company").notNull(),
  companyInitials: text("company_initials").notNull(),
  location: text("location").notNull(),
  workMode: text("work_mode").notNull(),
  url: text("url").notNull(),
  description: text("description").notNull(),
  postedDate: date("posted_date", { mode: "string" }).notNull(),
  salaryRange: text("salary_range").notNull(),
  fetchedAt: timestamp("fetched_at", { withTimezone: true })
    .notNull()
    .defaultNow(),
  relevanceScore: integer("relevance_score").notNull(),
  matchReasons: text("match_reasons").array().notNull(),
  highlightedSkills: text("highlighted_skills").array().notNull(),
  tailoredBullets: text("tailored_bullets").array().notNull(),
  coverLetter: text("cover_letter").notNull(),
  status: text("status").notNull().default("queued"),
  // Internal-only marker (not part of the public API contract, stripped by
  // response Zod schemas) distinguishing bootstrap seed rows from listings
  // fetched from real sources, so seed cleanup never touches real data.
  isSeed: boolean("is_seed").notNull().default(false),
  // Internal-only marker (not part of the public API contract, stripped by
  // response Zod schemas like isSeed above) indicating tailoredBullets/
  // coverLetter were generated by the AI tailoring pass (lib/ai/tailor.ts)
  // rather than the static placeholder in lib/sources/tailoring.ts.
  aiGenerated: boolean("ai_generated").notNull().default(false),
  // Red/green flag verdict from the AI fit-analysis pass (lib/ai/fit-analysis.ts).
  // Null until analyzed. Exposed in the public API contract (nullable).
  fitAnalysis: jsonb("fit_analysis").$type<FitAnalysis>(),
  // When fitAnalysis was last (re)computed. Internal-only, not part of the
  // public API contract - used only to gate the fit-analysis pass.
  fitAnalyzedAt: timestamp("fit_analyzed_at", { withTimezone: true }),
});

export type JobListing = typeof jobListingsTable.$inferSelect;
export type InsertJobListing = typeof jobListingsTable.$inferInsert;