import {
  bigint,
  boolean,
  index,
  integer,
  jsonb,
  pgTable,
  primaryKey,
  text,
  timestamp,
  uuid,
} from "drizzle-orm/pg-core";
import { postingsTable } from "./postings";
import { usersTable } from "./users";

/** The AI fit-analysis pass's verdict on how well a job matches the candidate. */
export type FitVerdict = "strong" | "good" | "stretch" | "poor";

/**
 * Shape stored in `user_postings.fit_analysis` (lib/ai/fit-analysis.ts).
 * Mirrors the `fitAnalysis` object in lib/api-spec/openapi.yaml.
 */
export type FitAnalysis = {
  verdict: FitVerdict;
  /** 3-5 concrete strengths matching this specific posting. */
  greenFlags: string[];
  /** 0-4 real concerns (seniority mismatch, visa/location, missing must-haves). */
  redFlags: string[];
  /** 0-4 skills the posting asks for that are absent from the resume. */
  gaps: string[];
};

/**
 * One user's relationship with one shared posting: their score for it, where
 * it sits in their review queue, and any AI output generated for them.
 *
 * Narrow on purpose - the expensive column (`description`) stays in
 * `postings`, so storage grows with the number of distinct adverts rather
 * than with the number of accounts.
 */
export const userPostingsTable = pgTable(
  "user_postings",
  {
    userId: uuid("user_id")
      .notNull()
      .references(() => usersTable.id, { onDelete: "cascade" }),
    postingId: bigint("posting_id", { mode: "number" })
      .notNull()
      .references(() => postingsTable.id, { onDelete: "cascade" }),
    relevanceScore: integer("relevance_score").notNull().default(0),
    matchReasons: text("match_reasons").array().notNull().default([]),
    highlightedSkills: text("highlighted_skills").array().notNull().default([]),
    status: text("status").notNull().default("queued"),
    tailoredBullets: text("tailored_bullets").array().notNull().default([]),
    coverLetter: text("cover_letter").notNull().default(""),
    // Internal-only marker (stripped by the response Zod schemas) indicating
    // tailoredBullets/coverLetter were generated by the AI tailoring pass
    // (lib/ai/tailor.ts) rather than the static placeholder in
    // lib/sources/tailoring.ts.
    aiGenerated: boolean("ai_generated").notNull().default(false),
    // Red/green flag verdict from the AI fit-analysis pass. Null until
    // analyzed. Exposed in the public API contract (nullable).
    fitAnalysis: jsonb("fit_analysis").$type<FitAnalysis>(),
    // When fitAnalysis was last (re)computed. Internal-only - used only to
    // gate the fit-analysis pass.
    fitAnalyzedAt: timestamp("fit_analyzed_at", { withTimezone: true }),
    createdAt: timestamp("created_at", { withTimezone: true })
      .notNull()
      .defaultNow(),
  },
  (table) => [
    primaryKey({ columns: [table.userId, table.postingId] }),
    index("user_postings_queue_idx").on(
      table.userId,
      table.status,
      table.relevanceScore,
    ),
  ],
);

export type UserPosting = typeof userPostingsTable.$inferSelect;
export type InsertUserPosting = typeof userPostingsTable.$inferInsert;
